#### PARAMETERS FILE ####

import os

## FOLDER PARAMETERS ##
AUDIO_PATH = os.path.join("Audio")
RAW_PATH = os.path.join("Raw")


## DATA PARAMETERS ##
AUDIO_SAMPLING_RATE = 16000
RAW_DATA_FRECUENCY = 100  # Hertz
MUSIC_DURATION = 60  # Seconds
SAMPLE_DURATION = 2  # Seconds
SAMPLES_PER_FILE = int(MUSIC_DURATION / SAMPLE_DURATION)


## NET PARAMETERS ##
LINEAR_OUT_DIM = 512
HIDDEN_DIM = 512
OUTPUT_DIM = 1+16
